### PR TITLE
fix: [ToolSets] Auth statuses incorrect after signin into ToolSet with special characters in name

### LINKED ISSUE #1011: [ToolSets] Auth statuses incorrect after signin into ToolSet with special characters in name
### Name and Version

dial-core

### What steps will reproduce the bug?

1. Create ToolSet with name containing " " character ("ToolSet 1").
2a. Signin into ToolSet with 'Global' credentials.
2b. Signin into ToolSet with 'User' credentials.
3. Get ToolSet.

### What is the expected behavior?

a. "global_auth_status" should be "SIGNED_IN"

b. "user_level_auth_status" should be "SIGNED_IN"

### What do you see instead?

a. "global_auth_status" is "SIGNED_OUT"

b. "user_level_auth_status" is "SIGNED_OUT"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1011

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetCredentialsController.java [hunk 1]
```diff
@@ -62,9 +63,10 @@ public Future<?> signIn() {
                     return taskExecutor.submit(() -> {
                         Deployment deployment = deploymentService.findDeployment(context, toolsetId);
                         if (deployment instanceof ToolSet toolSet) {
-                            verifyAccess(toolsetId, resourceSignInRequest.getCredentialsLevel());
+                            String encodedResourceUrl = UrlUtil.encodePath(toolsetId);
+                            verifyAccess(encodedResourceUrl, resourceSignInRequest.getCredentialsLevel());
                             CredentialsDescriptor credentialsDescriptor = CredentialsDescriptorFactory.fromAnyUrl(
-                                    toolsetId, resourceSignInRequest.getCredentialsLevel(), context);
+                                    encodedResourceUrl, resourceSignInRequest.getCredentialsLevel(), context);
```
Comment (oleksii-donets) [inline server/src/main/java/com/epam/aidial/core/server/controller/ToolSetCredentialsController.java:69]: Why don't we update CredentialsDescriptorFactory and CredentialsLocatorFactory factories instead?

File: server/src/test/java/com/epam/aidial/core/server/controller/ToolSetCredentialsControllerTest.java [hunk 2]
```diff
@@ -0,0 +1,324 @@
...
+    @Mock private EncryptionService encryptionService;
+    @Mock private DeploymentService deploymentService;
+    @Mock private Proxy proxy;
+    @Mock private HttpServerRequest request;
+
+    private ToolSetCredentialsController controller;
+
+    @BeforeEach
+    void setup() {
+        MockitoAnnotations.openMocks(this);
```
Comment (oleksii-donets) [inline server/src/test/java/com/epam/aidial/core/server/controller/ToolSetCredentialsControllerTest.java]: I am curious why not use @ExtendWith(MockitoExtension.class) instead? Seems clearer to me

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetCredentialsController.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply server/src/main/java/com/epam/aidial/core/server/controller/ToolSetCredentialsController.java:69]: in some places (com.epam.aidial.core.server.controller.ToolSetController#getToolSet for example) this url is already encoded, so it will break such cases.
we can think about refactoring later if we wanna streamline it across other services, but for this fix I prefer to keep it as it is.

File: server/src/test/java/com/epam/aidial/core/server/controller/ToolSetCredentialsControllerTest.java (hunk 2 above)
Comment (DmytroZaichenkoDev) [reply server/src/test/java/com/epam/aidial/core/server/controller/ToolSetCredentialsControllerTest.java]: fixed

**Review by oleksii-donets — APPROVED** [review]
