### PR TITLE
fix: [Toolsets] MCP request to application without toolset configuration results in 500 Internal Server Error #1483

### LINKED ISSUE #1483: [Toolsets] MCP request to application without toolset configuration results in 500 Internal Server Error
### Name and Version

ai-dial-core:latest

### What steps will reproduce the bug?

1. Configure the application without the `mcp` section, for example:
```json
{
  "applications": {
    "test-app": {
      "displayName": "Test Application",
      "description": "For testing purposes only",
      "endpoint": "http://<app host>/openai/deployments/test-app/chat/completions",
      "forwardAuthToken": true
    }
  }
}
```
2. Try connecting to the application tools, e.g.: `http://<dial core host>/v1/toolset/test-app/mcp`

### What is the expected behavior?

The server returns a 4xx status code and outputs a correct message to the log.

### What do you see instead?

<details>

<summary>Logs</summary>

> {"Body":"Responding with error. Body: Error occurred on processing MCP request by toolset: test-app","Attributes":{"instant":"2026-04-21T12:27:02.970200102Z","loggerName":"com.epam.aidial.core.server.ProxyContext","threadName":"vert.x-eventloop-thread-1","user.project":"STAT-GPT-2","user.id":null,"request.method":"POST","request.uri":"/v1/toolset/test-app/mcp","response.status":"Internal Server Error","response.status.code":500},"TraceId":"175e2d6a9e1bfe3fda73e66b7e000c31","SpanId":"f4d519f02b86c068","TraceFlags":"01","Timestamp":1776774422970000000,"ObservedTimestamp":1776774422970000000,"SeverityText":"WARN","SeverityNumber":13,"Resource":{"service.name":"aidial-core","service.version":"0.42.2"}}
> 2026-04-21T12:27:02.973379957Z {"Body":"Error occurred on processing MCP request by toolset: test-app","Attributes":{"instant":"2026-04-21T12:27:02.970868206Z","loggerName":"com.epam.aidial.core.server.controller.ToolSetProxyController","threadName":"vert.x-eventloop-thread-1","user.project":"STAT-GPT-2","user.id":null,"request.method":"POST","request.uri":"/v1/toolset/test-app/mcp","response.status":"Internal Server Error","response.status.code":500,"error":true,"exception.type":"java.lang.IllegalArgumentException","exception.message":"Application doesn't support MCP protocol: test-app","exception.stacktrace":"java.lang.IllegalArgumentException: Application doesn't support MCP protocol: test-app\n\tat com.epam.aidial.core.server.controller.ToolSetProxyController.resolveMcpProperties(ToolSetProxyController.java:172)\n\tat com.epam.aidial.core.server.controller.ToolSetProxyController.lambda$handle$0(ToolSetProxyController.java:143)\n\tat com.epam.aidial.core.server.vertx.AsyncTaskExecutor.lambda$submit$0(AsyncTaskExecutor.java:54)\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:240)\n\tat com.epam.aidial.core.server.vertx.AsyncTaskExecutor.lambda$submit$1(AsyncTaskExecutor.java:52)\n\tat java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)\n\tat java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\n"},"TraceId":"175e2d6a9e1bfe3fda73e66b7e000c31","SpanId":"f4d519f02b86c068","TraceFlags":"01","Timestamp":1776774422970000000,"ObservedTimestamp":1776774422970000000,"SeverityText":"ERROR","SeverityNumber":17,"Resource":{"service.name":"aidial-core","service.version":"0.42.2"}}

</details>

<details>

<summary>Response</summary>

Image

</details>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by astsiapanay**
fixes #1483

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: server/src/test/java/com/epam/aidial/core/server/ToolSetApiTest.java [hunk 1]
```diff
@@ -462,6 +462,27 @@ void testToolSetListing() {
...
+        String mcpRequest = """
+                {
+                   "payload": "foo"
+                }
+                """;
+
+        Response resp = send(HttpMethod.POST, "/v1/toolset/applications/3CcedGxCx23EwiVbVmscVktScRyf46KypuBQ65miviST/my%20app/mcp",
+                null, mcpRequest, "Content-type", "application/json");
+        // application doesn't support MCP interface
+        assertEquals(400, resp.status());
```
Comment (Oleksii-Klimov) [inline server/src/test/java/com/epam/aidial/core/server/ToolSetApiTest.java:483]: Shouldn't it be 404 if the endpoint is missing?

**Review by Oleksii-Klimov — APPROVED** [review]
