### PR TITLE
fix: Auth statuses incorrect after signin into ToolSet

### LINKED ISSUE #1008: [ToolSets] Auth statuses incorrect after signin into ToolSet
### Name and Version

dial-core

### What steps will reproduce the bug?

1a. Signin into ToolSet with "Global" credentials.
2a. Get ToolSet and check "global_auth_status" property.

1b. Signin into ToolSet with "USER" credentials.
2b. Get ToolSet and check "user_level_auth_status" property.

### What is the expected behavior?

a. "global_auth_status" should be "SIGNED_IN"

b. "user_level_auth_status" should be "SIGNED_IN"

### What do you see instead?

a. "global_auth_status" is "SIGNED_OUT"

b. "user_level_auth_status" is "SIGNED_OUT"

### Additional information

Intermittent issue. Might be reproduced after few signin operations and when some of credentails from previous signins are expired.

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1008

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthSettingsService.java [hunk 1]
```diff
@@ -71,18 +71,25 @@ private boolean shouldRegisterResourceDynamically(ResourceAuthSettings resourceA
...
     private void setUserAuthStatus(ResourceAuthSettings resourceAuthSettings,
-                                   List<ResourceCredentials> resourceCredentialsList) {
+                                   List<ResourceCredentials> resourceCredentialsList,
+                                   String userSub) {
         Optional<ResourceCredentials> userResourceCredentials = resourceCredentialsList.stream()
-                .filter(resourceCredentials -> resourceCredentials.getCredentialsLevel().equals(CredentialsLevel.USER))
+                .filter(resourceCredentials -> resourceCredentials.getCredentialsLevel().equals(CredentialsLevel.USER)
+                    && resourceCredentials.getAuthenticationType().equals(AuthenticationType.OAUTH)
+                    && resourceCredentials.getUserSub() != null
+                    && resourceCredentials.getUserSub().equals(userSub)
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthSettingsService.java]: Nit. That might be more simple to check 
userSub.equals(credentials.getUserSub()) since userSub can’t be null.

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthSettingsService.java [hunk 2]
```diff
@@ -71,18 +71,25 @@ private boolean shouldRegisterResourceDynamically(ResourceAuthSettings resourceA
...
+                    && !resourceCredentials.isTokenExpired())
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthSettingsService.java:88]: What if user has multiple credentials and we always take the first one. The rest of ones won’t be updated. Why?

Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthSettingsService.java:88]: Eventually, user won't have more then one personal credentials of some type (OAUTH for example) for single ToolSet. This would be implemented in separate PR's. 

So the idea here is to find if user has at least one non-expired credentials of some type. in our case it's OAUTH type, USER level. It's enough for Auth Status calculation.

**Review by astsiapanay — APPROVED** [review]
