### PR TITLE
fix: [Toolsets] Decode gzip-encoded OAuth discovery responses #1493

### LINKED ISSUE #1493: 400 bad request (schema validation error) when saving external mcp toolset in quickapp
### Name and Version

0.42.2

### What steps will reproduce the bug?

Backend returns  400 bad request error during the save process of an external mcp toolset within quickapp, citing a payload schema mismatch.

1. Create new quickApp
2. Add external endpoint for mcp toolset
3. Select Ouath authentication with login
4. Save changes

Image

### What is the expected behavior?

quickapp should be saved successfully, and a 200 OK or 201 Created response should be returned

### What do you see instead?

The request fails with a 400 Bad Request with error message: "Payload does not match the required schema" 

Image

Image

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
CDN-fronted OAuth servers (e.g., Akamai) may return Content-Encoding: gzip regardless of the client's Accept-Encoding. Java's built-in HttpClient does not auto-decompress, so ResourceAuthorizationClient now reads the response as bytes and decodes gzip bodies when the header is present.

### Applicable issues

- fixes #1493

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java [hunk 1]
```diff
@@ -116,6 +118,23 @@ private static boolean hasUnresolvedAddressException(Throwable ex) {
...
+    // Some OAuth servers (e.g., CDN-fronted) return Content-Encoding: gzip even when the client
+    // did not request it. Java's built-in HttpClient does not auto-decompress, so we do it here.
+    @SneakyThrows
+    private static String decodeBody(HttpResponse<byte[]> response) {
+        byte[] body = response.body();
+        if (body == null || body.length == 0) {
+            return "";
+        }
+        String encoding = response.headers().firstValue("Content-Encoding").orElse("");
+        if ("gzip".equalsIgnoreCase(encoding)) {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java]: Content encoding may have multiple values separated by comma. Please see examples how we check content type in other controllers using Strings.CI.contains

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java [hunk 2]
```diff
@@ -116,6 +118,23 @@ private static boolean hasUnresolvedAddressException(Throwable ex) {
...
+            try (GZIPInputStream gzip = new GZIPInputStream(new ByteArrayInputStream(body))) {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java:144]: I think we should check in advance the encoding is gzip and add warning if encoding is not supported

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java (hunk 2 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceAuthorizationClient.java:144]: fixed

**Review by astsiapanay — APPROVED** [review]
