### PR TITLE
fix: Error creating ToolSet with API_KEY auth type

### LINKED ISSUE #1004: [ToolSets] Error creating ToolSet with API_KEY auth type
### Name and Version

dial-core

### What steps will reproduce the bug?

1. Create ToolSet with authentication_type = 'API_KEY'.
2. Get ToolSet created in previous step.

### What is the expected behavior?

ToolSet should have authentication_type = 'API_KEY' in 'auth_settings' section.

### What do you see instead?

ToolSet has authentication_type = 'OAUTH' in 'auth_settings' section.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1004 

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: server/src/main/java/com/epam/aidial/core/server/service/credentials/ToolSetAuthSettingsService.java [hunk 1]
```diff
@@ -32,13 +32,13 @@ public void initToolsetAuthSettings(ToolSet toolSet) {
                 throw new IllegalArgumentException("ToolSetAuthSettings is not defined for ToolSet: " + toolSet.getName());
             }
 
-            if (toolSetAuthSettings.getAuthenticationType() == AuthenticationType.NONE) {
+            toolSetAuthSettingsValidator.validate(toolSetAuthSettings);
+
+            if (toolSetAuthSettings.getAuthenticationType() != AuthenticationType.OAUTH) {
```
Comment (astsiapanay) [inline server/src/main/java/com/epam/aidial/core/server/service/credentials/ToolSetAuthSettingsService.java:37]: should we register toolset even for auth type `NONE`?

Comment (DmytroZaichenkoDev) [reply server/src/main/java/com/epam/aidial/core/server/service/credentials/ToolSetAuthSettingsService.java:37]: no, we shouldn't and wont do it. it will be registered for OAUTH type only.

**Review by astsiapanay — APPROVED** [review]
