### PR TITLE
fix: [Applications] Add validation for interceptors and dependencies #1423

### LINKED ISSUE #1423: [Applications] Add validation for `interceptors` and `dependencies`
### Name and Version

dial

### What steps will reproduce the bug?

Send request to Core to create application with unknown `interceptors` and `dependencies`

Image

### What is the expected behavior?

Core should return either 400 or 404 stating that `interceptors` and `dependencies` not found

### What do you see instead?

Core successfully created application with unknown `interceptors` and `dependencies`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by astsiapanay**
fixes #1423

### CODE REVIEW

**Review by utafrali — COMMENTED** [review]
The validation logic is conceptually correct and the switch-expression refactor in `handleError` is a clean improvement. The main issue is the `catch (Exception e)` that masks unexpected server-side failures as client errors (400). The test additions cover rejection paths but are missing a happy-path case to guard against over-rejection regressions.

File: server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java [hunk 1]
```diff
@@ -224,8 +228,23 @@ private void validateCustomApplication(Application application) {
...
+                for (String interceptor : application.getInterceptors()) {
+                    if (!config.getInterceptors().containsKey(interceptor)) {
+                        throw new HttpException(BAD_REQUEST, "Unknown interceptor: " + interceptor);
+                    }
+                }
+            }
+            for (String dependency : application.getDependencies()) {
+                try {
+                    deploymentService.findDeployment(context, dependency);
+                } catch (Exception e) {
```
Comment (utafrali) [inline server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java]: The `catch (Exception e)` is too broad. `findDeployment` can throw `ResourceNotFoundException`, `PermissionDeniedException`, and `IllegalArgumentException` for expected failure cases -- but catching all `Exception` means an unexpected runtime fault (e.g., a Redis timeout or NullPointerException inside the service) is swallowed and returned to the client as a 400 BAD_REQUEST instead of a 500 INTERNAL_SERVER_ERROR. Narrow this to the specific expected exceptions:

```java
} catch (ResourceNotFoundException | PermissionDeniedException | IllegalArgumentException e) {
    throw new HttpException(BAD_REQUEST, "Unknown or forbidden dependency: " + dependency);
}
```

Unexpected exceptions will then propagate normally and be handled by `handleError`.

File: server/src/test/java/com/epam/aidial/core/server/CustomApplicationApiTest.java [hunk 2]
```diff
@@ -110,6 +111,36 @@ void testApplicationCreation() {
...
+                "endpoint": "http://application1/v1/completions",
+                "display_name": "My Custom Application",
+                "display_version": "1.0",
+                "icon_url": "http://application1/icon.svg",
+                "description": "My Custom Application Description",
+                "interceptors": ["unknown-interceptor"]
+                }
+                """, "authorization", "admin");
+        verify(response, 400);
+
```
Comment (utafrali) [inline server/src/test/java/com/epam/aidial/core/server/CustomApplicationApiTest.java:143]: The tests cover the rejection cases (unknown dependency, unknown interceptor), but there is no assertion that valid, known dependencies and valid interceptors are *accepted*. Without a happy-path test, a bug that rejects all dependencies would not be caught. Consider adding a PUT that references a known deployment in `dependencies` and verifies the response is 200.

File: server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java (hunk 1 above)
Comment (utafrali) [inline server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java]: When a dependency exists but the requesting user lacks read access, `findDeployment` throws `PermissionDeniedException` and this code returns 400 BAD_REQUEST with message "Unknown or forbidden dependency". The status is debatable -- a 403 would more accurately reflect the real reason -- but if the intent is to avoid leaking the existence of inaccessible resources, the current message and status are a reasonable security trade-off. Just worth documenting the rationale with a brief inline comment so future readers understand the choice.

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java (hunk 1 above)
Comment (astsiapanay) [reply server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java]: fixed

Comment (astsiapanay) [reply server/src/main/java/com/epam/aidial/core/server/controller/ResourceController.java]: fixed

File: server/src/test/java/com/epam/aidial/core/server/CustomApplicationApiTest.java (hunk 2 above)
Comment (astsiapanay) [reply server/src/test/java/com/epam/aidial/core/server/CustomApplicationApiTest.java:143]: fixed

**Review by Oleksii-Klimov — APPROVED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by astsiapanay** [comment]
/deploy-review

>GitHub actions run: [24559459116](https://github.com/epam/ai-dial-ci/actions/runs/24559459116)

| Stage                        | Status         |
| ---------------------------- | -------------- |
| [deploy-review](https://chat-ai-dial-core-pr-1472.gke.test.dial.parts) | [Success ✅](https://github.com/epam/ai-dial-ci/actions/runs/24559459116/job/71804173434) |
| chat | [Success ✅](https://github.com/epam/ai-dial-ci/actions/runs/24559459116/job/71806583225) |
