### PR TITLE
fix: [Toolsets] Toolset with expired login token return 404 in response instead of 401

### LINKED ISSUE #1504: Toolset with expired login token return 404 in response instead of 401
### Name and Version

latest

### What steps will reproduce the bug?

Preconditions:
there is some notion toolset which is displayed as logged in on Chat UI, but was not user for some hours ( real state or toolset might be logged out)

Steps:

1. create quick app 2.0
2. add toolset from preconditions
3. type prompt to trigger toolset in preview part (e.g. what is my notion account)

### What is the expected behavior?

quick app trigger attached toolset and response is generated without errors in stages
for logged out toolset login form appeared

### What do you see instead?

response contain initialization error
logs contain response code 404 instead of 401

Image

Note: after regenerate response login form appeared

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1504
- fixes Decrypt clientSecret on OAuth token refresh

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetMcpProxyController.java [hunk 1]
```diff
@@ -45,7 +48,7 @@ protected void validateDeployment(Deployment deployment) {
     @Override
     protected void injectProxyRequestHeaders(HttpClientRequest proxyRequest, MultiMap excludeHeaders) {
         ResourceCredentials resourceCredentials = resourceCredentialsService.getRefreshedResourceCredentials(
-                credentialsLocator, toolSet.getAuthSettings(), context.getInitiatorId()
+                credentialsLocator, authSettingsResolver.resolve(toolSet, context), context.getInitiatorId()
```
Comment (astsiapanay) [inline server/src/main/java/com/epam/aidial/core/server/controller/ToolSetMcpProxyController.java]: Let's do not inline method's call. Please keep it as a new var.

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetToolsController.java [hunk 2]
```diff
@@ -345,7 +348,7 @@ private String getUpstreamEndpoint(Deployment deployment) {
     private void injectToolsetCredentials(HttpClientRequest proxyRequest, Deployment deployment) {
         if (deployment instanceof ToolSet toolSet) {
             ResourceCredentials resourceCredentials = resourceCredentialsService.getRefreshedResourceCredentials(
-                    credentialsLocator, toolSet.getAuthSettings(), context.getInitiatorId()
+                    credentialsLocator, authSettingsResolver.resolve(toolSet, context), context.getInitiatorId()
```
Comment (astsiapanay) [inline server/src/main/java/com/epam/aidial/core/server/controller/ToolSetToolsController.java]: The same thing

Comment (DmytroZaichenkoDev) [reply server/src/main/java/com/epam/aidial/core/server/controller/ToolSetToolsController.java]: fixed

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetMcpProxyController.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply server/src/main/java/com/epam/aidial/core/server/controller/ToolSetMcpProxyController.java]: fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by astsiapanay — APPROVED** [review]
