### PR TITLE
fix: ToolSets API doesn't provide GET endpoint for calling MCP via SSE protocol

### LINKED ISSUE #1056: [ToolSet] ToolSets API doesn't provide GET endpoint for calling MCP via SSE protocol
### Name and Version

dial-core

### What steps will reproduce the bug?

1. Create ToolSet using remote MCP server, which supports SSE protocol. (e.g. https://mcp.deepwiki.com/sse)
2. Create Quick App 2.0 and add MCP server from step 1.
3. Start chat with the app.

### What is the expected behavior?

App responds without any errors.

### What do you see instead?

App responds with error message.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1056 

### Description of changes

- Adds GET /v1/toolset/{id}/mcp endpoint.
- Makes 'code_challenge_method' property optional on ToolSet creation.
- Makes 'scopes_supported' property retrieved from Protected resource metadata using Auth server metadata as fallback.
- Fixes format for ./well-known urls for getting Protected resource and Auth server metadata

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/registration/ResourceRegistrationStrategy.java [hunk 1]
```diff
@@ -9,29 +9,34 @@
...
-                || supportedMethods.isEmpty()
-                || supportedMethods.contains(CodeChallengeMethod.S256.getValue())
-                ? CodeChallengeMethod.S256.getValue()
-                : supportedMethods.getFirst();
+    default Optional<String> getCodeChallengeMethod(AuthorizationServerMetadata metadata) {
+        return Optional.ofNullable(metadata.getCodeChallengeMethodsSupported())
+                .filter(codeChallengeMethodsSupported -> !codeChallengeMethodsSupported.isEmpty())
+                .map(codeChallengeMethodsSupported -> codeChallengeMethodsSupported.contains(CodeChallengeMethod.S256.getValue())
+                        ? CodeChallengeMethod.S256.getValue()
+                        : CodeChallengeMethod.PLAIN.getValue());
```
Comment (oleksii-donets) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/registration/ResourceRegistrationStrategy.java]: Shouldn't we check that PLAIN code challenge method is contained in the list as well, and throw an error if we don't support any of provided code challenge methods?

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetController.java [hunk 2]
```diff
@@ -79,7 +79,6 @@ private List<ToolSet> getResourceToolSets() {
             public ToolSet extract(ResourceDescriptor resource, ProxyContext context) {
                 ToolSet toolSet = toolSetService.getToolSet(context, resource).getValue();
                 toolSet.clearAuthSettings();
-                resourceAuthSettingsService.setResourceAuthStatuses(toolSet.getName(), toolSet.getAuthSettings(), context.getUserSub());
```
Comment (oleksii-donets) [inline server/src/main/java/com/epam/aidial/core/server/controller/ToolSetController.java:82]: why is this removed?

**Review by oleksii-donets — DISMISSED** [review]

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/registration/ResourceRegistrationStrategy.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/registration/ResourceRegistrationStrategy.java]: error would be thrown later, but agree, that we could do it here. 
fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

File: server/src/main/java/com/epam/aidial/core/server/controller/ToolSetController.java (hunk 2 above)
Comment (DmytroZaichenkoDev) [reply server/src/main/java/com/epam/aidial/core/server/controller/ToolSetController.java:82]: we already doing the same in service. line 80

**Review by oleksii-donets — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>Scanned Files</h2>
None

**Review by oleksii-donets — APPROVED** [review]

**Comment by DmytroZaichenkoDev** [comment]
SSE flow under investigation. API will be documented later after fixing SSE usage.
