### PR TITLE
fix: [ToolSets] Logout from ToolSet throws an error

### LINKED ISSUE #1065: [ToolSets] Logout from ToolSet throws an error
### Name and Version

dial-core

### What steps will reproduce the bug?

1. Create ToolSet.
2. Login into ToolSet.
3. Logout from ToolSet

### What is the expected behavior?

Logout succeeded

### What do you see instead?

500 Internal Server Error

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1065

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td><a href=https://github.com/jakartaee/validation> maven/jakarta.validation:jakarta.validation-api </a></td><td>3.0.0</td>
      <td>:green_circle: 7.7</td><td><details><summary>Details</summary><table><tr><th>Check</th><th>Score</th><th>Reason</th></tr><tr><td>Dangerous-Workflow</td><td>:green_circle: 10</td><td>no dangerous workflow patterns detected</td></tr><tr><td>Token-Permissions</td><td>:green_circle: 10</td><td>GitHub workflow tokens follow principle of least privilege</td></tr><tr><td>Code-Review</td><td>:green_circle: 5</td><td>Found 4/8 approved changesets -- score normalized to 5</td></tr><tr><td>Binary-Artifacts</td><td>:green_circle: 9</td><td>binaries present in source code</td></tr><tr><td>Packaging</td><td>:warning: -1</td><td>packaging workflow not detected</td></tr><tr><td>Maintained</td><td>:green_circle: 10</td><td>18 commit(s) and 0 issue activity found in the last 90 days -- score normalized to 10</td></tr><tr><td>Pinned-Dependencies</td><td>:green_circle: 10</td><td>all dependencies are pinned</td></tr><tr><td>CII-Best-Practices</td><td>:warning: 0</td><td>no effort to earn an OpenSSF best practices badge detected</td></tr><tr><td>Fuzzing</td><td>:warning: 0</td><td>project is not fuzzed</td></tr><tr><td>License</td><td>:green_circle: 10</td><td>license file detected</td></tr><tr><td>Signed-Releases</td><td>:warning: -1</td><td>no releases found</td></tr><tr><td>Branch-Protection</td><td>:warning: -1</td><td>internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration</td></tr><tr><td>Vulnerabilities</td><td>:green_circle: 10</td><td>0 existing vulnerabilities detected</td></tr><tr><td>Security-Policy</td><td>:green_circle: 10</td><td>security policy file detected</td></tr><tr><td>SAST</td><td>:warning: 0</td><td>SAST tool is not run on all commits -- score normalized to 0</td></tr></table></details></td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java [hunk 1]
```diff
@@ -89,26 +92,29 @@ public List<ResourceCredentials> getAllResourceCredentials(CredentialsLocator cr
...
-        if (resourceSignOutRequest.getCredentialsLevel().equals(CredentialsLevel.GLOBAL)) {
-            removed = resourceCredentialsList.removeIf(
-                    resourceCredentials -> resourceCredentials.getCredentialsLevel().equals(resourceSignOutRequest.getCredentialsLevel()));
-        } else if (resourceSignOutRequest.getCredentialsLevel().equals(CredentialsLevel.USER)) {
-            removed = resourceCredentialsList.removeIf(
-                    resourceCredentials -> resourceCredentials.getCredentialsLevel().equals(resourceSignOutRequest.getCredentialsLevel())
-                            && resourceCredentials.getUserSub().equals(userSub));
+        if (signOutRequestCredentialsLevel.equals(CredentialsLevel.USER)) {
+            String savedCredentialsUserSub = resourceCredentials.getUserSub();
+            Objects.requireNonNull(savedCredentialsUserSub, "Invalid saved credentials: missing userSub");
```
Comment (oleksii-donets) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: What if a user accessed the DIAL API using an API KEY, instead of a Token. Then there wouldn't be any user sub.

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java [hunk 2]
```diff
@@ -89,26 +92,29 @@ public List<ResourceCredentials> getAllResourceCredentials(CredentialsLocator cr
     public boolean deleteResourceCredentials(CredentialsLocator credentialsLocator,
                                              ResourceSignOutRequest resourceSignOutRequest,
                                              String userSub) {
-        List<ResourceCredentials> resourceCredentialsList = resourceCredentialsService.getAllResourceCredentials(credentialsLocator);
+        log.debug("Start deleting credentials for resource: {}.", credentialsLocator.getResourceId());
+        CredentialsLevel signOutRequestCredentialsLevel = resourceSignOutRequest.getCredentialsLevel();
+        CredentialsDescriptor credentialsDescriptor = credentialsLocator.getCredentialsDescriptors().get(signOutRequestCredentialsLevel);
```
Comment (oleksii-donets) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: The problem with this logic is that it is not transactional: get, then act. As a solution, the delete method could be modified to accept a predicate, and resourceService.computeResourceBytes should be used instead of resourceService.deleteResource

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java [hunk 3]
```diff
@@ -89,26 +92,29 @@ public List<ResourceCredentials> getAllResourceCredentials(CredentialsLocator cr
...
+        ResourceCredentials resourceCredentials = resourceCredentialsService.getResourceCredentials(credentialsDescriptor);
```
Comment (i-am-v-alexander-v) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: The method getResourceCredentials can return null (as seen in ResourceCredentialsService.java:58-60), but there's no null check before accessing it. This will cause NPE when trying to delete non-existent credentials.

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java [hunk 4]
```diff
@@ -89,26 +92,29 @@ public List<ResourceCredentials> getAllResourceCredentials(CredentialsLocator cr
...
+        if (signOutRequestCredentialsLevel.equals(CredentialsLevel.USER)) {
+            String savedCredentialsUserSub = resourceCredentials.getUserSub();
+            Objects.requireNonNull(savedCredentialsUserSub, "Invalid saved credentials: missing userSub");
+            if (!savedCredentialsUserSub.equals(userSub)) {
+                throw new IllegalArgumentException("Can't delete other user's personal credentials");
+            }
         }
 
-        resourceCredentialsService.updateAllResourceCredentials(credentialsLocator, resourceCredentialsList);
+        boolean removed = resourceCredentialsService.deleteResourceCredentials(credentialsDescriptor);
```
Comment (i-am-v-alexander-v) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: Currently, any authenticated user can delete GLOBAL credentials?
If yes, then the authorization check is applied only at the USER level, and there is no restriction preventing regular users from deleting organization-wide GLOBAL credentials.
This looks like a critical security issue and should be addressed.

Comment (i-am-v-alexander-v) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: There is a time gap between reading the credentials (line 98) and deleting them (line 115).
During this window, another thread could modify or delete the credentials, which may lead to an inconsistent state.

**Comment by i-am-v-alexander-v** [comment]
Please provide tests for these scenarios:

- Non-admin users cannot delete GLOBAL credentials
- Users cannot delete other users' credentials
- NPE scenario when credentials don't exist
- Concurrent modification scenarios

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td><a href=https://github.com/jakartaee/validation> maven/jakarta.validation:jakarta.validation-api </a></td><td>3.0.0</td>
      <td>:green_circle: 7.7</td><td><details><summary>Details</summary><table><tr><th>Check</th><th>Score</th><th>Reason</th></tr><tr><td>Dangerous-Workflow</td><td>:green_circle: 10</td><td>no dangerous workflow patterns detected</td></tr><tr><td>Token-Permissions</td><td>:green_circle: 10</td><td>GitHub workflow tokens follow principle of least privilege</td></tr><tr><td>Code-Review</td><td>:green_circle: 5</td><td>Found 4/8 approved changesets -- score normalized to 5</td></tr><tr><td>Binary-Artifacts</td><td>:green_circle: 9</td><td>binaries present in source code</td></tr><tr><td>Packaging</td><td>:warning: -1</td><td>packaging workflow not detected</td></tr><tr><td>Maintained</td><td>:green_circle: 10</td><td>18 commit(s) and 0 issue activity found in the last 90 days -- score normalized to 10</td></tr><tr><td>Pinned-Dependencies</td><td>:green_circle: 10</td><td>all dependencies are pinned</td></tr><tr><td>CII-Best-Practices</td><td>:warning: 0</td><td>no effort to earn an OpenSSF best practices badge detected</td></tr><tr><td>Fuzzing</td><td>:warning: 0</td><td>project is not fuzzed</td></tr><tr><td>License</td><td>:green_circle: 10</td><td>license file detected</td></tr><tr><td>Signed-Releases</td><td>:warning: -1</td><td>no releases found</td></tr><tr><td>Branch-Protection</td><td>:warning: -1</td><td>internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration</td></tr><tr><td>Vulnerabilities</td><td>:green_circle: 10</td><td>0 existing vulnerabilities detected</td></tr><tr><td>Security-Policy</td><td>:green_circle: 10</td><td>security policy file detected</td></tr><tr><td>SAST</td><td>:warning: 0</td><td>SAST tool is not run on all commits -- score normalized to 0</td></tr></table></details></td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: as far as I know, userSub will always be present

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java (hunk 2 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: fixed and moved to ResourceCredentialsService

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java (hunk 3 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: fixed and moved to ResourceCredentialsService

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java (hunk 4 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: This check is implemented in controller:
com.epam.aidial.core.server.controller.ToolSetCredentialsController#verifyAccess

Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsManager.java]: fixed and moved to ResourceCredentialsService

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java [hunk 5]
```diff
@@ -60,102 +82,92 @@ public ResourceCredentials getResourceCredentials(CredentialsDescriptor credenti
...
-            );
-        }
-    }
+    public boolean deleteResourceCredentials(CredentialsLocator credentialsLocator,
+                                             ResourceSignOutRequest resourceSignOutRequest,
+                                             String userSub) {
+        log.debug("Deleting resource credentials for resourceId={}.", credentialsLocator.getResourceId());
+        CredentialsLevel signOutRequestCredentialsLevel = resourceSignOutRequest.getCredentialsLevel();
+        CredentialsDescriptor credentialsDescriptor = credentialsLocator.getCredentialsDescriptors().get(signOutRequestCredentialsLevel);
+        AtomicBoolean deleteSucceeded = new AtomicBoolean(false);
```
Comment (oleksii-donets) [inline credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java]: Is it better to use org.apache.commons.lang3.mutable.MutableObject - that's the standard practice for the project

**Review by oleksii-donets — DISMISSED** [review]

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java (hunk 5 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java]: fixed

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td><a href=https://github.com/jakartaee/validation> maven/jakarta.validation:jakarta.validation-api </a></td><td>3.0.0</td>
      <td>:green_circle: 7.7</td><td><details><summary>Details</summary><table><tr><th>Check</th><th>Score</th><th>Reason</th></tr><tr><td>Dangerous-Workflow</td><td>:green_circle: 10</td><td>no dangerous workflow patterns detected</td></tr><tr><td>Token-Permissions</td><td>:green_circle: 10</td><td>GitHub workflow tokens follow principle of least privilege</td></tr><tr><td>Code-Review</td><td>:green_circle: 5</td><td>Found 4/8 approved changesets -- score normalized to 5</td></tr><tr><td>Binary-Artifacts</td><td>:green_circle: 9</td><td>binaries present in source code</td></tr><tr><td>Packaging</td><td>:warning: -1</td><td>packaging workflow not detected</td></tr><tr><td>Maintained</td><td>:green_circle: 10</td><td>18 commit(s) and 0 issue activity found in the last 90 days -- score normalized to 10</td></tr><tr><td>Pinned-Dependencies</td><td>:green_circle: 10</td><td>all dependencies are pinned</td></tr><tr><td>CII-Best-Practices</td><td>:warning: 0</td><td>no effort to earn an OpenSSF best practices badge detected</td></tr><tr><td>Fuzzing</td><td>:warning: 0</td><td>project is not fuzzed</td></tr><tr><td>License</td><td>:green_circle: 10</td><td>license file detected</td></tr><tr><td>Signed-Releases</td><td>:warning: -1</td><td>no releases found</td></tr><tr><td>Branch-Protection</td><td>:warning: -1</td><td>internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration</td></tr><tr><td>Vulnerabilities</td><td>:green_circle: 10</td><td>0 existing vulnerabilities detected</td></tr><tr><td>Security-Policy</td><td>:green_circle: 10</td><td>security policy file detected</td></tr><tr><td>SAST</td><td>:warning: 0</td><td>SAST tool is not run on all commits -- score normalized to 0</td></tr></table></details></td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

File: credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java (hunk 5 above)
Comment (oleksii-donets) [reply credentials/src/main/java/com/epam/aidial/core/credentials/service/ResourceCredentialsService.java]: initialize it with a default value, otherwise there would be NPE
`new MutableObject<>(false)`

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td><a href=https://github.com/jakartaee/validation> maven/jakarta.validation:jakarta.validation-api </a></td><td>3.0.0</td>
      <td>:green_circle: 7.7</td><td><details><summary>Details</summary><table><tr><th>Check</th><th>Score</th><th>Reason</th></tr><tr><td>Dangerous-Workflow</td><td>:green_circle: 10</td><td>no dangerous workflow patterns detected</td></tr><tr><td>Token-Permissions</td><td>:green_circle: 10</td><td>GitHub workflow tokens follow principle of least privilege</td></tr><tr><td>Code-Review</td><td>:green_circle: 5</td><td>Found 4/8 approved changesets -- score normalized to 5</td></tr><tr><td>Binary-Artifacts</td><td>:green_circle: 9</td><td>binaries present in source code</td></tr><tr><td>Packaging</td><td>:warning: -1</td><td>packaging workflow not detected</td></tr><tr><td>Maintained</td><td>:green_circle: 10</td><td>18 commit(s) and 0 issue activity found in the last 90 days -- score normalized to 10</td></tr><tr><td>Pinned-Dependencies</td><td>:green_circle: 10</td><td>all dependencies are pinned</td></tr><tr><td>CII-Best-Practices</td><td>:warning: 0</td><td>no effort to earn an OpenSSF best practices badge detected</td></tr><tr><td>Fuzzing</td><td>:warning: 0</td><td>project is not fuzzed</td></tr><tr><td>License</td><td>:green_circle: 10</td><td>license file detected</td></tr><tr><td>Signed-Releases</td><td>:warning: -1</td><td>no releases found</td></tr><tr><td>Branch-Protection</td><td>:warning: -1</td><td>internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration</td></tr><tr><td>Vulnerabilities</td><td>:green_circle: 10</td><td>0 existing vulnerabilities detected</td></tr><tr><td>Security-Policy</td><td>:green_circle: 10</td><td>security policy file detected</td></tr><tr><td>SAST</td><td>:warning: 0</td><td>SAST tool is not run on all commits -- score normalized to 0</td></tr></table></details></td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by oleksii-donets — DISMISSED** [review]

**Review by i-am-v-alexander-v — DISMISSED** [review]

**Comment by ai-dial-actions** [comment]
<h1>Dependency Review</h1>
✅ No vulnerabilities or license issues or OpenSSF Scorecard issues found.<h2>OpenSSF Scorecard</h2>
<table><tr><th>Package</th><th>Version</th><th>Score</th><th>Details</th></tr>
<tr><td><a href=https://github.com/jakartaee/validation> maven/jakarta.validation:jakarta.validation-api </a></td><td>3.0.0</td>
      <td>:green_circle: 7.7</td><td><details><summary>Details</summary><table><tr><th>Check</th><th>Score</th><th>Reason</th></tr><tr><td>Dangerous-Workflow</td><td>:green_circle: 10</td><td>no dangerous workflow patterns detected</td></tr><tr><td>Token-Permissions</td><td>:green_circle: 10</td><td>GitHub workflow tokens follow principle of least privilege</td></tr><tr><td>Code-Review</td><td>:green_circle: 5</td><td>Found 4/8 approved changesets -- score normalized to 5</td></tr><tr><td>Binary-Artifacts</td><td>:green_circle: 9</td><td>binaries present in source code</td></tr><tr><td>Packaging</td><td>:warning: -1</td><td>packaging workflow not detected</td></tr><tr><td>Maintained</td><td>:green_circle: 10</td><td>18 commit(s) and 0 issue activity found in the last 90 days -- score normalized to 10</td></tr><tr><td>Pinned-Dependencies</td><td>:green_circle: 10</td><td>all dependencies are pinned</td></tr><tr><td>CII-Best-Practices</td><td>:warning: 0</td><td>no effort to earn an OpenSSF best practices badge detected</td></tr><tr><td>Fuzzing</td><td>:warning: 0</td><td>project is not fuzzed</td></tr><tr><td>License</td><td>:green_circle: 10</td><td>license file detected</td></tr><tr><td>Signed-Releases</td><td>:warning: -1</td><td>no releases found</td></tr><tr><td>Branch-Protection</td><td>:warning: -1</td><td>internal error: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration</td></tr><tr><td>Vulnerabilities</td><td>:green_circle: 10</td><td>0 existing vulnerabilities detected</td></tr><tr><td>Security-Policy</td><td>:green_circle: 10</td><td>security policy file detected</td></tr><tr><td>SAST</td><td>:warning: 0</td><td>SAST tool is not run on all commits -- score normalized to 0</td></tr></table></details></td></tr>
</table><h2>Scanned Files</h2>
<ul><li>settings.gradle</li></ul>

**Review by i-am-v-alexander-v — APPROVED** [review]
