### PR TITLE
fix: Support more Remote MCP servers in DIAL ToolSets

### LINKED ISSUE #1030: [ToolSets] Support more Remote MCP servers in DIAL ToolSets
### Name and Version

dial-core

### What is the problem this feature will solve?

Some Remote MCP servers is not supported by DIAL ToolSets.

### What is the feature you are proposing to solve the problem?

Dynamically retrieving configuration details such as endpoints (e.g., authorization, token, and registration endpoints) and supported capabilities (e.g., grant types, code challenge methods, etc.).

https://datatracker.ietf.org/doc/html/rfc9728#name-use-of-www-authenticate-for

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by DmytroZaichenkoDev**
### Applicable issues

- fixes #1030

### Description of changes

- Adds support for Servers, which does not provide referesh tokens (e.g. github).
- Implements approach using WWW-Authenticate HTTP response header for retrieving MCP server's metadata:
(https://datatracker.ietf.org/doc/html/rfc9728#name-use-of-www-authenticate-for).
- Introduces clean Fallback mechanism for MCP server's metadata retrieval.
- Adds metadata validation.

### Checklist

- [X] Title of the pull request follows [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java [hunk 1]
```diff
@@ -18,13 +18,31 @@ public class ResourceCredentials {
     private String refreshToken;
     private long createdAt;
     private long updatedAt;
-    private long expiresIn;
+    private Long expiresIn;
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: Add javadoc or rename the field to `expiresInSeconds`

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java [hunk 2]
```diff
@@ -18,13 +18,31 @@ public class ResourceCredentials {
...
-        return true;
+
+        return !hasRefreshToken() || isAccessTokenWithinExpiry();
+    }
+
+    public boolean needsRefresh() {
+        return hasRefreshToken() && !isTokenAlive();
+    }
+
+    private boolean hasRefreshToken() {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: the method's name doesn't reflect the logic it's implemented. That may confuse a reader

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java [hunk 3]
```diff
@@ -18,13 +18,31 @@ public class ResourceCredentials {
...
+        return refreshToken != null && expiresIn != null;
+    }
+
+    private boolean isAccessTokenWithinExpiry() {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: Perhaps the method should have better naming e.g. `isExpired`

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java [hunk 4]
```diff
@@ -18,13 +18,31 @@ public class ResourceCredentials {
...
+        if (updatedAt <= 0 || expiresIn == null || expiresIn <= 0) {
+            return false;
+        }
+
+        long expiryTimeInMillis = updatedAt + expiresIn * 1000;
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: expiresIn * 1000 -> TimUnit.SECONDS.toMillis(expiresIn)

File: credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+
+import lombok.experimental.UtilityClass;
+
+import java.net.http.HttpHeaders;
+import java.util.Map;
+import java.util.Optional;
+import java.util.stream.Collectors;
+
+@UtilityClass
+public class HeaderUtils {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java]: The class is used in a single place. I don't think it's a good candidate to be an utility class.

File: credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+    private static final String WWW_AUTHENTICATE_HEADER = "WWW-Authenticate";
+    private static final String RESOURCE_METADATA_PARAMETER = "resource_metadata=";
+
+    /**
+     * Handles extracting the resource metadata URL from the WWW-Authenticate header.
+     *
+     * @param headers Map of response headers.
+     * @return Optional metadata URL if found.
+     */
+    public static Optional<String> extractMetadataUrl(Map<String, String> headers) {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java]: Add Unit tests

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java (hunk 1 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java (hunk 2 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java (hunk 3 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java (hunk 4 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java (hunk 5 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java]: fixed

File: credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java (hunk 6 above)
Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/util/HeaderUtils.java]: added

File: credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java [hunk 7]
```diff
@@ -18,13 +20,35 @@ public class ResourceCredentials {
...
     private long createdAt;
     private long updatedAt;
-    private long expiresIn;
+    private Long expiresInSeconds;
     private String userSub;
 
-    public boolean isTokenExpired() {
-        if (authenticationType.equals(AuthenticationType.OAUTH)) {
-            return updatedAt + expiresIn * 1000 <= System.currentTimeMillis();
+    public boolean hasUnexpiredToken() {
```
Comment (astsiapanay) [inline credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java:26]: I would add Unit tests to some methods. Despite on the methods seems to be simple they have conditional branches.

Comment (DmytroZaichenkoDev) [reply credentials/src/main/java/com/epam/aidial/core/credentials/data/credentials/ResourceCredentials.java:26]: fixed

**Review by astsiapanay — APPROVED** [review]

**Comment by astsiapanay** [comment]
/deploy-review
>GitHub actions run: [17578279751](https://github.com/epam/ai-dial-ci/actions/runs/17578279751)
>Environment URL: [review-environment](https://chat-ai-dial-core-pr-1031.nightly-test.deltixhub.io) | [pipeline](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/681391)
>Chat E2E tests status: [success](https://github.com/epam/ai-dial-ci/actions/runs/17578279751)
>Overlay E2E tests status: [success](https://github.com/epam/ai-dial-ci/actions/runs/17578279751)
